# Generated by Django 3.1.2 on 2020-10-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
    ]
