# Generated by Django 3.1.2 on 2021-02-02 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mrs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processtypestatus',
            name='process_type',
            field=models.ForeignKey(db_column='processTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.processtype'),
        ),
        migrations.AddField(
            model_name='processtypestatus',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='part',
            field=models.ForeignKey(db_column='partId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.part'),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='status',
            field=models.ForeignKey(db_column='statusId', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.processtypestatus'),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='workorder',
            field=models.ForeignKey(db_column='workorderId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.workorder'),
        ),
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='brandId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.brand'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplierId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.supplier'),
        ),
        migrations.AddField(
            model_name='mrsfield',
            name='operators',
            field=models.ManyToManyField(to='mrs.MrsOperator'),
        ),
        migrations.AddField(
            model_name='metadatavalue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrs.metadatatype'),
        ),
        migrations.AddField(
            model_name='metadatatype',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='maintenancemonth',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='maintenancemonth',
            name='tasks_templates',
            field=models.ManyToManyField(to='mrs.TaskTemplate'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.customer'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.job'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='lifts',
            field=models.ManyToManyField(to='mrs.Lift'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='notes',
            field=models.ManyToManyField(to='mrs.Note'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_areas',
            field=models.ManyToManyField(to='mrs.ServiceArea'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_target',
            field=models.ForeignKey(db_column='serviceTargetId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.servicetarget'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_types',
            field=models.ManyToManyField(to='mrs.ServiceType'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.ForeignKey(db_column='statusId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.processtypestatus'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.technician'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='workorder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrs.workorder'),
        ),
        migrations.AddField(
            model_name='lift',
            name='brand',
            field=models.ForeignKey(db_column='brandId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.brand'),
        ),
        migrations.AddField(
            model_name='lift',
            name='job',
            field=models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.job'),
        ),
        migrations.AddField(
            model_name='lift',
            name='status',
            field=models.ForeignKey(blank=True, db_column='statusId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.processtypestatus'),
        ),
        migrations.AddField(
            model_name='job',
            name='agent',
            field=models.ForeignKey(db_column='agentId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.agent'),
        ),
        migrations.AddField(
            model_name='job',
            name='contract',
            field=models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.contract'),
        ),
        migrations.AddField(
            model_name='job',
            name='documents',
            field=models.ManyToManyField(to='mrs.FileDocument'),
        ),
        migrations.AddField(
            model_name='job',
            name='group',
            field=models.ForeignKey(blank=True, db_column='groupId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.group'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='job',
            name='round',
            field=models.ForeignKey(db_column='roundId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.round'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(db_column='statusId', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.processtypestatus'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='part',
            field=models.ForeignKey(blank=True, db_column='partId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.part'),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='content_type',
            field=models.ForeignKey(blank=True, db_column='contentTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fault',
            name='service_target_id',
            field=models.ForeignKey(db_column='serviceTargetId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.servicetarget'),
        ),
        migrations.AddField(
            model_name='customer',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='correction',
            name='service_target_id',
            field=models.ForeignKey(db_column='serviceTargetId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.servicetarget'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrs.contact'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(db_column='statusId', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.processtypestatus'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrs.address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.ForeignKey(blank=True, db_column='position_id', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='position', to='mrs.metadatavalue'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.ForeignKey(blank=True, db_column='title_id', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='title', to='mrs.metadatavalue'),
        ),
        migrations.AddField(
            model_name='agent',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mrs.contact'),
        ),
        migrations.AddField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project'),
        ),
        migrations.AddField(
            model_name='actionshistory',
            name='content_type',
            field=models.ForeignKey(db_column='contentTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
    ]
