# Generated by Django 3.1.2 on 2021-02-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0002_auto_20210202_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
