# Generated by Django 3.1.2 on 2021-02-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0003_auto_20210203_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='mrs.FileDocument'),
        ),
    ]
