# Generated by Django 3.1.2 on 2021-02-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0004_auto_20210203_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='unlocale',
            new_name='un_locale',
        ),
    ]
