# Generated by Django 3.1.2 on 2021-02-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0006_auto_20210204_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jhaitem',
            name='is_active',
            field=models.BooleanField(db_column='isActive', default=True),
        ),
        migrations.AlterField(
            model_name='jhaitem',
            name='is_ticked_default',
            field=models.BooleanField(db_column='isTickedDefault', default=False),
        ),
        migrations.AlterField(
            model_name='lift',
            name='is_active',
            field=models.BooleanField(db_column='isActive', default=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(db_column='isActive', default=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='lifts',
            field=models.ManyToManyField(blank=True, null=True, to='mrs.Lift'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service_areas',
            field=models.ManyToManyField(blank=True, null=True, to='mrs.ServiceArea'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service_types',
            field=models.ManyToManyField(blank=True, null=True, to='mrs.ServiceType'),
        ),
    ]
