# Generated by Django 3.1.2 on 2021-02-24 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mrs', '0009_auto_20210205_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammedTask',
            fields=[
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('filter', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('conditions', models.JSONField()),
                ('content_type', models.ForeignKey(db_column='contentTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mrs.project')),
            ],
            options={
                'db_table': 'programmed_task',
                'managed': True,
            },
        ),
    ]
